### PR TITLE
Changes to work with BS4 via reactstrap

### PR DESCRIPTION
**Pull request by autarch**
Note that the CSS change will not work well if you want the form label to be
left of the input, as opposed to above it.

### CODE REVIEW

**Comment by autarch** [comment]
Hi Yuri. First, thanks for this code. It's really helpful!

Second, I don't expect you to merge this now. I wanted to share it in case you are considering moving this to BS4, and also for the benefit of anyone else who wants to use this component with reactstrap.

**Comment by yury-dymov** [comment]
Thank you for the contribution! 

I am not merging atm but after bs4 will be release might do so. 

I also suspect package.json should be updated as well.

**Comment by autarch** [comment]
Ah, good call on `package.json`. I'm not sure it's worth making the change in this PR right. The reactstrap package is still in a bit of flux. I'm using an alpha release of v5, but by the time BS4 is released as stable reactstrap should have a stable v5.

**Comment by yury-dymov** [comment]
Well, let's see how things are evolved. I have too many emerging technologies in my project already and slightly tired of the constant disruptions :)

**Comment by autarch** [comment]
Haha. I strongly suggest programming in _anything but JS_ then ;)

As a long-time Perl and less long-time Go programmer the amount of churn in the JS space is overwhelming and baffling for me.

**Comment by yury-dymov** [comment]
I am on elixir-graphql on the backend (cool thing) and react-apollo on the frontend :)
Yeah, JS is insane. Article I wrote a year ago is obsolete trash already

**Pull request closed without merging**
